"""empty message

Revision ID: b575156bdecc
Revises: 916e176e937e
Create Date: 2017-05-01 20:51:54.688395

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'b575156bdecc'
down_revision = '916e176e937e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidadesresponsaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidadesresponsaveis_nome'), 'unidadesresponsaveis', ['nome'], unique=True)
    op.create_table('unidadesconsumidoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('id_unidade_responsavel', sa.Integer(), nullable=True),
    sa.Column('localizacao', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('num_cliente', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('mod_tarifaria', sa.String(length=64), nullable=False),
    sa.Column('num_medidores', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_unidade_responsavel'], ['unidadesresponsaveis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_cliente'),
    sa.UniqueConstraint('num_medidores')
    )
    op.create_index(op.f('ix_unidadesconsumidoras_nome'), 'unidadesconsumidoras', ['nome'], unique=True)
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_unidade_consumidora', sa.Integer(), nullable=True),
    sa.Column('data_leitura', sa.Date(), nullable=False),
    sa.Column('cons_fora_ponta', sa.Integer(), nullable=False),
    sa.Column('cons_hora_ponta', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_unidade_consumidora'], ['unidadesconsumidoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_data_leitura'), 'contas', ['data_leitura'], unique=False)
    op.drop_index('idx_blocos_localizacao', table_name='blocos')
    op.drop_index('idx_campi_mapeamento', table_name='campi')
    op.drop_index('idx_centros_mapeamento', table_name='centros')
    op.drop_index('idx_subestacoes_abrigadas_localizacao', table_name='subestacoes_abrigadas')
    op.drop_index('idx_subestacoes_aereas_localizacao', table_name='subestacoes_aereas')
    op.add_column(u'usuarios', sa.Column('id_unidade_responsavel', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'unidadesresponsaveis', ['id_unidade_responsavel'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column(u'usuarios', 'id_unidade_responsavel')
    op.create_index('idx_subestacoes_aereas_localizacao', 'subestacoes_aereas', ['localizacao'], unique=False)
    op.create_index('idx_subestacoes_abrigadas_localizacao', 'subestacoes_abrigadas', ['localizacao'], unique=False)
    op.create_index('idx_centros_mapeamento', 'centros', ['mapeamento'], unique=False)
    op.create_index('idx_campi_mapeamento', 'campi', ['mapeamento'], unique=False)
    op.create_index('idx_blocos_localizacao', 'blocos', ['localizacao'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint(u'(srid > 0) AND (srid <= 998999)', name=u'spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_contas_data_leitura'), table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_unidadesconsumidoras_nome'), table_name='unidadesconsumidoras')
    op.drop_table('unidadesconsumidoras')
    op.drop_index(op.f('ix_unidadesresponsaveis_nome'), table_name='unidadesresponsaveis')
    op.drop_table('unidadesresponsaveis')
    # ### end Alembic commands ###
